# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房名称')),
                ('address', models.CharField(max_length=200, verbose_name='机房地址')),
                ('phone', models.CharField(max_length=15, verbose_name='机房联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='机房联系email')),
                ('letter', models.CharField(max_length=5, verbose_name='idc 字母简称')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户登录名')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
            ],
            options={
                'db_table': 'dashboard_user',
            },
        ),
    ]
